/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author ASUS
 */
public class VistaMenuPrincipal extends javax.swing.JDialog {
    /**
     * Estado de la vista, conociendo los botones accionados.
     */
    private int estado;

    public int getEstado() {
        return estado;
    }
    
    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal(java.awt.Frame parent, boolean modal ) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnTaller = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        foindo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Simulador ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btnEntrar.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorderPainted(false);
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 130, 200, 180));

        btnTaller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/taller (1).png"))); // NOI18N
        btnTaller.setBorderPainted(false);
        btnTaller.setContentAreaFilled(false);
        btnTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTallerActionPerformed(evt);
            }
        });
        getContentPane().add(btnTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        foindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoMenu (1).jpg"))); // NOI18N
        getContentPane().add(foindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Se ingresa a la simulación del vehículo.
     * @param evt 
     */
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        estado = 1;
        dispose();
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * Se ingresa al taller, para poder modificar el vehículo.
     * @param evt 
     */
    private void btnTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTallerActionPerformed
        estado = 2;
        dispose();
    }//GEN-LAST:event_btnTallerActionPerformed

    /**
     * Se sale de la aplicación.
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnTaller;
    private javax.swing.JLabel foindo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
